name: Update README

on:
  push:
    branches:
      - main # Change this to your default branch if not 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update README
      run: |
        DATE=$(git log -1 --format="%cd" --date=iso-strict)
        DATE_TIME=$(TZ=America/New_York date -d "$DATE" +"%b %e, %Y at %l:%M%p")
        sed -i "s/Last change: .*/Last change: $DATE_TIME/" README.md
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Update README with latest commit date and time"
        git remote set-url origin https://x-access-token:${{ secrets.UPDATE_README_PAT }}@github.com/andr3wV/andr3wV.github.io.git
        git push