name: Update README

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update README
      run: |
        DATE=$(git log -1 --format="%cd" --date=short)
        sed -i "s/Last change: .*/Last change: $DATE/" README.md
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Update README with latest commit date"
        git push